language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0

matrix:
  include:
    - php: 5.6
      env: COMPOSER_FLAGS='--prefer-lowest' SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      env: SYMFONY_VERSION='2.7.*' SYMFONY_DEPRECATIONS_HELPER=weak
    - php: 7.0
      env: SYMFONY_VERSION='2.8.*'
    - php: 7.0
      env: SYMFONY_VERSION='3.1.*'
  fast_finish: true

before_install:
  - nvm install
  - npm install
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: npm test
